packages:
  - '**'
  - '!node_modules'
ignoredBuiltDependencies:
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - es5-ext
  - esbuild
  - vue-demi
patchedDependencies:
  '@dcloudio/uni-h5': patches/@dcloudio__uni-h5.patch
